### PR TITLE
start postfix at runtime if sendmail is used

### LINKED ISSUE #232: Mail subscriptions don't work
I have attempted most everything to get email subscriptions working in the Docker image. I am able to sign-up for subscriptions however I don't receive the verification email or any of the notification emails. Is there anything wrong in my docker-compose?

```
version: "3"

services:
  postgres:
    image: postgres:9.5
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=[redacted]
      - POSTGRES_PASSWORD=[redacted]
    restart: always
  cachet:
    build:
      context: .
      args:
        - cachet_ver=v2.3.12
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=[redacted]
      - DB_PASSWORD=[redacted]
      - APP_KEY=base64:[redacted]
      - DEBUG=true
      - MAIL_DRIVER=sendmail
      - MAIL_NAME=My\sName
      - MAIL_ADDRESS=me@example.com
      - MAIL_USERNAME=me@example.com
      - QUEUE_DRIVER=database
    depends_on:
      - postgres
    restart: always
```
 I receive the following errors when I add a subscriber:
```
cachet_1    | [2017-09-19 16:41:52] Failed: mailer@handleQueuedMessage
cachet_1    | 2017-09-19 16:41:52,243 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140055294849680 for <Subprocess at 140055296069216 with name queue-worker in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Invalid seek [/usr/lib/python2.7/site-packages/supervisor/supervisord.py|runforever|235] [/usr/lib/python2.7/site-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/site-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/site-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/site-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/site-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/site-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/site-packages/supervisor/loggers.py|doRollover|211])
```

### PR DESCRIPTION
**Pull request by Stunkymonkey**
@djdefi this is the correct fix for sendmail

it checks if `sendmail` is selected. If so then postfix is used. otherwise everything stays the same

fixes #232

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -67,6 +67,12 @@ check_configured() {
   esac
 }
 
+check_sendmail() {
+	if [[ ${MAIL_DRIVER} == "sendmail" ]]; then
+		sudo postfix start
```
Comment (bebehei) [inline entrypoint.sh:72]: sbin should not be in PATH, so if I'd expect the postfix command won't be found

(in the sudoers file you explicitly state the full postfix path)

Comment (Stunkymonkey) [reply entrypoint.sh:72]: `postifx` is started correctly, but changing this will not hurt at all.

**Comment by Stunkymonkey** [comment]
if someone is wondering, why this effort is needed: postfix only wants to run under root user
